server:
  port: 10003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    password: zheng
  redis:
#    Redis 单机单实例
    host: 47.111.143.81
    database: 1
    port: 6379
    password: zheng
#    哨兵模式
#    database: 1
#    password: zheng
#    sentinel:
#      master: zheng-master
#      nodes: 192.168.1.191:26379,192.168.1.192:26379,192.168.1.193:26379
#    集群模式
#    password: zheng
#    cluster:
#      nodes: 192.168.1.201:6379,192.168.1.202:6379, 192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379, 192.168.1.206:6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Ribbon全局配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000

#Ribbon指定服务配置超时判定，优先级更高
foodie-user-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true

#Feign的超时判定，优先级高于Ribbon
feign:
  client:
    config:
      #      全局默认配置
      default:
        connectTimeout: 1000
        readTimeout: 3000
#        优先级最高
      foodie-user-service:
        connectTimeout: 1000
        readTimeout: 3000

